"""PDF layout for the Commercial Invoice and Packing List (ReportLab). Prints computed values only."""

from decimal import Decimal
from io import BytesIO
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.enums import TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import KeepTogether, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.services.documents.compute import TBC, Invoice, PackingList

FOOTER = "Generated by ExportAgent – verify before use"
_INK = colors.HexColor("#18181b")
_MUTED = colors.HexColor("#71717a")
_RULE = colors.HexColor("#d4d4d8")
_HEAD = colors.HexColor("#f4f4f5")
_WARN = colors.HexColor("#b91c1c")

_base = getSampleStyleSheet()
TEXT = ParagraphStyle("text", parent=_base["Normal"], fontName="Helvetica", fontSize=8.5, leading=11, textColor=_INK)
SMALL = ParagraphStyle("small", parent=TEXT, fontSize=7.5, leading=9.5, textColor=_MUTED)
LABEL = ParagraphStyle("label", parent=SMALL, fontName="Helvetica-Bold", textColor=_MUTED)
BOLD = ParagraphStyle("bold", parent=TEXT, fontName="Helvetica-Bold")
NUMBER = ParagraphStyle("number", parent=TEXT, alignment=TA_RIGHT)
NUMBER_BOLD = ParagraphStyle("number_bold", parent=BOLD, alignment=TA_RIGHT)
TITLE = ParagraphStyle("title", parent=TEXT, fontName="Helvetica-Bold", fontSize=15, leading=18, alignment=TA_RIGHT)
EXPORTER = ParagraphStyle("exporter", parent=TEXT, fontName="Helvetica-Bold", fontSize=12, leading=15)


def _value(value: object, style: ParagraphStyle = TEXT) -> Paragraph:
    text = escape(str(value))
    if text == TBC:
        text = f'<font color="#b91c1c"><b>{TBC}</b></font>'
    return Paragraph(text, style)


def _money(amount: Decimal | None, places: int = 2) -> str:
    return TBC if amount is None else f"{amount:,.{places}f}"


def _number(value: int | Decimal | None, places: int = 0) -> str:
    return TBC if value is None else f"{value:,.{places}f}"


def _footer(canvas, doc) -> None:
    canvas.saveState()
    canvas.setFont("Helvetica", 7.5)
    canvas.setFillColor(_MUTED)
    canvas.drawString(15 * mm, 10 * mm, FOOTER)
    canvas.drawRightString(A4[0] - 15 * mm, 10 * mm, f"Page {doc.page}")
    canvas.restoreState()


def _header(exporter: str, address: str, title: str, number: str, on: str) -> Table:
    table = Table(
        [[
            [Paragraph(escape(exporter), EXPORTER), Paragraph(escape(address), SMALL)],
            [Paragraph(escape(title), TITLE),
             Paragraph(f"No. <b>{escape(number)}</b><br/>Date {escape(on)}", ParagraphStyle("r", parent=TEXT, alignment=TA_RIGHT))],
        ]],
        colWidths=[105 * mm, 75 * mm],
    )
    table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LINEBELOW", (0, 0), (-1, 0), 1.2, _INK),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
    ]))
    return table


def _to_confirm(fields: list[str]) -> list:
    if not fields:
        return []
    box = Table(
        [[Paragraph(
            f'<font color="#b91c1c"><b>To be confirmed before use ({len(fields)}):</b></font> '
            + escape(", ".join(fields)),
            TEXT,
        )]],
        colWidths=[180 * mm],
    )
    box.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 0.8, _WARN),
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#fef2f2")),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    return [Spacer(1, 4 * mm), box]


def _shipment_line(shipment: str | None) -> list:
    return [Spacer(1, 3 * mm), Paragraph(f"<b>{escape(shipment)}</b> (part shipment)", TEXT)] if shipment else []


def _grid(pairs: list[tuple[str, object]], columns: int = 2) -> Table:
    """Label/value pairs in a grid, `columns` pairs per row."""
    rows, row = [], []
    for label, value in pairs:
        row += [Paragraph(escape(label), LABEL), _value(value)]
        if len(row) == columns * 2:
            rows.append(row)
            row = []
    if row:
        rows.append(row + [""] * (columns * 2 - len(row)))
    width = 180 * mm / columns
    table = Table(rows, colWidths=[width * 0.36, width * 0.64] * columns)
    table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LINEBELOW", (0, 0), (-1, -1), 0.4, _RULE),
        ("LEFTPADDING", (0, 0), (-1, -1), 2),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    return table


def _lines_table(header: list[str], rows: list[list], widths: list[float], totals: list) -> Table:
    data = [[Paragraph(f"<b>{escape(h)}</b>", SMALL) for h in header], *rows, totals]
    table = Table(data, colWidths=[w * mm for w in widths], repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), _HEAD),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LINEBELOW", (0, 0), (-1, 0), 0.8, _INK),
        ("LINEBELOW", (0, 1), (-1, -2), 0.3, _RULE),
        ("LINEABOVE", (0, -1), (-1, -1), 0.8, _INK),
        ("LEFTPADDING", (0, 0), (-1, -1), 3),
        ("RIGHTPADDING", (0, 0), (-1, -1), 3),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    return table


def _signature(exporter: str) -> KeepTogether:
    return KeepTogether([
        Spacer(1, 10 * mm),
        Paragraph(f"For <b>{escape(exporter)}</b>", TEXT),
        Spacer(1, 12 * mm),
        Paragraph("Authorised signatory", SMALL),
    ])


def _build(story: list) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, leftMargin=15 * mm, rightMargin=15 * mm,
                            topMargin=14 * mm, bottomMargin=18 * mm, title="ExportAgent document",
                            author="ExportAgent")
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buffer.getvalue()


def render_invoice(invoice: Invoice) -> bytes:
    places = 0 if invoice.currency == "JPY" else 2
    story = [_header(invoice.exporter_name, invoice.exporter_address, invoice.title, invoice.number, invoice.date)]
    story += _shipment_line(invoice.shipment)
    story += _to_confirm(invoice.tbc_fields)
    story += [
        Spacer(1, 4 * mm),
        _grid([(label, value) for label, value in invoice.registration], columns=2),
        Spacer(1, 3 * mm),
        _grid([
            ("Buyer", invoice.buyer), ("Consignee", invoice.consignee),
            ("Notify party", invoice.notify_party), ("Buyer PO", invoice.po_number),
            ("Style", invoice.style), ("Currency", invoice.currency),
            ("Incoterm", f"{invoice.incoterm} {invoice.named_place}" if TBC not in (invoice.incoterm, invoice.named_place) else TBC),
            ("Payment terms", invoice.payment_terms),
            ("Port of loading", invoice.port_of_loading), ("Port of discharge", invoice.port_of_discharge),
            ("Country of origin", invoice.country_of_origin), ("Final destination", invoice.final_destination),
        ]),
        Spacer(1, 5 * mm),
    ]
    rows = [
        [_value(line.description, SMALL), _value(line.colour), _value(line.hs_code),
         Paragraph(_number(line.quantity), NUMBER), _value(_money(line.unit_price, max(places, 2)), NUMBER),
         _value(_money(line.amount, places), NUMBER)]
        for line in invoice.lines
    ]
    totals = ["", Paragraph("<b>Total</b>", TEXT), "", Paragraph(f"<b>{_number(invoice.total_quantity)}</b>", NUMBER),
              Paragraph(escape(invoice.currency), NUMBER_BOLD), _value(_money(invoice.total_amount, places), NUMBER_BOLD)]
    story.append(_lines_table(
        ["Description of goods", "Colour", "HS code", "Quantity (pcs)", f"Unit price ({invoice.currency})",
         f"Amount ({invoice.currency})"],
        rows, [56, 26, 20, 24, 26, 28], totals,
    ))
    story += [
        Spacer(1, 3 * mm),
        Paragraph(f"<b>Amount in words:</b> {escape(invoice.amount_in_words)}"
                  if invoice.amount_in_words != TBC else f"<b>Amount in words:</b> <font color='#b91c1c'><b>{TBC}</b></font>", TEXT),
        Spacer(1, 5 * mm),
        Paragraph("Declarations", LABEL),
        *[Paragraph(escape(text), TEXT) for text in invoice.declarations],
        Spacer(1, 4 * mm),
        Paragraph("Bank details", LABEL),
        _grid(invoice.bank, columns=1),
        _signature(invoice.exporter_name),
    ]
    return _build(story)


def render_packing_list(packing: PackingList) -> bytes:
    story = [_header(packing.exporter_name, packing.exporter_address, "PACKING LIST", packing.number, packing.date)]
    story += _shipment_line(packing.shipment)
    story += _to_confirm(packing.tbc_fields)
    story += [
        Spacer(1, 4 * mm),
        _grid([
            ("Buyer", packing.buyer), ("Buyer PO", packing.po_number),
            ("Invoice no.", packing.invoice_number), ("Style", packing.style),
            ("Description", packing.description), ("Carton size (cm)", packing.carton_dimensions_cm),
        ]),
        Spacer(1, 5 * mm),
    ]
    rows = [
        [Paragraph(f"{r.carton_from}" if r.carton_from == r.carton_to else f"{r.carton_from}–{r.carton_to}", TEXT),
         _value(r.colour), _value(r.size), Paragraph(_number(r.pcs_per_carton), NUMBER),
         Paragraph(_number(r.cartons), NUMBER), Paragraph(_number(r.quantity), NUMBER),
         _value(_number(r.net_kg, 2), NUMBER), _value(_number(r.gross_kg, 2), NUMBER)]
        for r in packing.rows
    ]
    totals = [Paragraph("<b>Total</b>", TEXT), "", "", "",
              Paragraph(f"<b>{_number(packing.total_cartons)}</b>", NUMBER),
              Paragraph(f"<b>{_number(packing.total_quantity)}</b>", NUMBER),
              _value(_number(packing.total_net_kg, 2), NUMBER_BOLD),
              _value(_number(packing.total_gross_kg, 2), NUMBER_BOLD)]
    story.append(_lines_table(
        ["Carton nos.", "Colour", "Size", "Pcs / carton", "Cartons", "Pieces", "Net wt (kg)", "Gross wt (kg)"],
        rows, [22, 30, 20, 20, 18, 20, 24, 26], totals,
    ))
    story += [
        Spacer(1, 3 * mm),
        Paragraph(f"<b>Total volume:</b> {_number(packing.total_cbm, 3)} CBM" if packing.total_cbm is not None
                  else f"<b>Total volume:</b> <font color='#b91c1c'><b>{TBC}</b></font>", TEXT),
    ]
    if packing.notes:
        story += [Spacer(1, 3 * mm), Paragraph("Notes", LABEL)]
        story += [Paragraph(escape(note), SMALL) for note in packing.notes]
    story.append(_signature(packing.exporter_name))
    return _build(story)
