"""initial schema

Revision ID: 1ad5de341dcb
Revises: 
Create Date: 2026-10-01 15:10:05.205697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1ad5de341dcb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer', sa.String(length=200), nullable=False),
    sa.Column('po_number', sa.String(length=100), nullable=False),
    sa.Column('style', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('profile', sa.String(length=50), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('buyer', 'po_number', name='uq_orders_buyer_po')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_buyer'), ['buyer'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_po_number'), ['po_number'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('po_version', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_order_id'), ['order_id'], unique=False)

    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('classification', sa.JSON(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emails_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_status'), ['status'], unique=False)

    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rounds', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_email_id'), ['email_id'], unique=False)

    op.create_table('email_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_attachments_email_id'), ['email_id'], unique=False)

    op.create_table('po_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.JSON(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'version', name='uq_po_versions_order_version')
    )
    with op.batch_alter_table('po_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_po_versions_order_id'), ['order_id'], unique=False)

    op.create_table('agent_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('input', sa.JSON(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_steps_run_id'), ['run_id'], unique=False)

    op.create_table('drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('edited_body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drafts_email_id'), ['email_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drafts_status'), ['status'], unique=False)

    op.create_table('llm_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.String(length=40), nullable=False),
    sa.Column('tier', sa.String(length=10), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_calls_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_calls_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_calls_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_calls_task_type'), ['task_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_calls_task_type'))
        batch_op.drop_index(batch_op.f('ix_llm_calls_run_id'))
        batch_op.drop_index(batch_op.f('ix_llm_calls_model'))
        batch_op.drop_index(batch_op.f('ix_llm_calls_created_at'))

    op.drop_table('llm_calls')
    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drafts_status'))
        batch_op.drop_index(batch_op.f('ix_drafts_email_id'))

    op.drop_table('drafts')
    with op.batch_alter_table('agent_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_steps_run_id'))

    op.drop_table('agent_steps')
    with op.batch_alter_table('po_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_po_versions_order_id'))

    op.drop_table('po_versions')
    with op.batch_alter_table('email_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_attachments_email_id'))

    op.drop_table('email_attachments')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_email_id'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emails_status'))
        batch_op.drop_index(batch_op.f('ix_emails_order_id'))

    op.drop_table('emails')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_order_id'))

    op.drop_table('documents')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_po_number'))
        batch_op.drop_index(batch_op.f('ix_orders_buyer'))

    op.drop_table('orders')
    # ### end Alembic commands ###
