"""email analysis, llm call source, llm cache

Revision ID: 68b7c239f647
Revises: 1ad5de341dcb
Create Date: 2026-10-06 18:51:38.683772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '68b7c239f647'
down_revision: Union[str, None] = '1ad5de341dcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_cache',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('response', sa.JSON(none_as_null=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('extraction', sa.JSON(none_as_null=True), nullable=True))
        batch_op.add_column(sa.Column('analysis_error', sa.Text(), nullable=True))
        batch_op.create_unique_constraint('uq_emails_external_id', ['external_id'])

    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=10), server_default='live', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.drop_column('source')

    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_constraint('uq_emails_external_id', type_='unique')
        batch_op.drop_column('analysis_error')
        batch_op.drop_column('extraction')
        batch_op.drop_column('external_id')

    op.drop_table('llm_cache')
    # ### end Alembic commands ###
