"""document number, profile and computed content

Revision ID: 7b679ad862b3
Revises: ffb51a0bdb95
Create Date: 2026-10-10 22:18:56.750392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7b679ad862b3'
down_revision: Union[str, None] = 'ffb51a0bdb95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('profile', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('data', sa.JSON(none_as_null=True), nullable=True))
        batch_op.add_column(sa.Column('tbc_fields', sa.JSON(none_as_null=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('tbc_fields')
        batch_op.drop_column('data')
        batch_op.drop_column('profile')
        batch_op.drop_column('number')

    # ### end Alembic commands ###
