"""escalations, agent trace, search cache

Revision ID: a63ea31d8ad8
Revises: c4fb40f41d19
Create Date: 2026-10-08 20:57:18.626471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a63ea31d8ad8'
down_revision: Union[str, None] = 'c4fb40f41d19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_cache',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('result', sa.JSON(none_as_null=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_agent_runs_order_id'), ['order_id'], unique=False)
        batch_op.create_foreign_key('fk_agent_runs_order_id_orders', 'orders', ['order_id'], ['id'])

    with op.batch_alter_table('agent_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('round', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('evidence_id', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('call_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_agent_steps_call_id_llm_calls', 'llm_calls', ['call_id'], ['id'])

    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detail', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.drop_column('detail')

    with op.batch_alter_table('agent_steps', schema=None) as batch_op:
        batch_op.drop_constraint('fk_agent_steps_call_id_llm_calls', type_='foreignkey')
        batch_op.drop_column('call_id')
        batch_op.drop_column('evidence_id')
        batch_op.drop_column('summary')
        batch_op.drop_column('round')

    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_agent_runs_order_id_orders', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_agent_runs_order_id'))
        batch_op.drop_column('result')
        batch_op.drop_column('order_id')

    op.drop_table('search_cache')
    # ### end Alembic commands ###
