"""po version basis

Revision ID: c4fb40f41d19
Revises: 68b7c239f647
Create Date: 2026-10-08 19:22:29.597143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c4fb40f41d19'
down_revision: Union[str, None] = '68b7c239f647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('po_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basis', sa.String(length=30), server_default='document', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('po_versions', schema=None) as batch_op:
        batch_op.drop_column('basis')

    # ### end Alembic commands ###
