"""draft review fields

Revision ID: ffb51a0bdb95
Revises: a63ea31d8ad8
Create Date: 2026-10-10 18:49:56.281290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ffb51a0bdb95'
down_revision: Union[str, None] = 'a63ea31d8ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('fact_check', sa.JSON(none_as_null=True), nullable=True))
        batch_op.add_column(sa.Column('call_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('reject_reason', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_drafts_call_id_llm_calls', 'llm_calls', ['call_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_drafts_call_id_llm_calls', type_='foreignkey')
        batch_op.drop_column('reject_reason')
        batch_op.drop_column('sent_at')
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('call_id')
        batch_op.drop_column('fact_check')
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
